### ISSUE TITLE
Likes website doesn't work 

### ISSUE THREAD

**Issue by EdenEitani** [asimptot/FollowerBot#29]
Hi, I ran get_instagram_likes, the website shows the success message but I don't See the likes on my page. 

(Tried manually and it's the same, maybe the site doesn't work anymore)

**Comment by asimptot** [comment]
@EdenEitani hi,

This issue is known. Can you try to use VPN, please? I prefer Hotspot Shield Free VPN and you can connect somewhere randomly. I can't set the website that sends likes and followers. I just track success logs and it returns pass. If your problem is still going on, please let me know.
