### ISSUE TITLE
Adding Soundcloud Play and Website Hits to youlikehits

### ISSUE THREAD

**Issue by saabtech** [asimptot/FollowerBot#5]
The youlikehits works Great, Looking forward if Soundcloud Play and Website Hits can be included to the script.

**Comment by asimptot** [comment]
@saabtech hi,

Since I don't have a Soundcloud Play account, I don't know how many credit I earn on YouLikeHits platform. If it brings more than Youtube View, I can implement it. By the way, Website Hits brings lee credit than Youtube View. You can add your social media platform whatever you like to spend your credit that you earned on Youtube View.

Don't forget i:

* Youtube View is to earn credit.
* You can add your social media account whatever you like to spend your credit.

**Comment by saabtech** [comment]
Allright, Thanks

> @saabtech hi,
> 
> Since I don't have a Soundcloud Play account, I don't know how many credit I earn on YouLikeHits platform. If it brings more than Youtube View, I can implement it. By the way, Website Hits brings lee credit than Youtube View. You can add your social media platform whatever you like to spend your credit that you earned on Youtube View.
> 
> Don't forget i:
> 
>     * Youtube View is to earn credit.
> 
>     * You can add your social media account whatever you like to spend your credit.

Allright, Thanks, the script works great.
